import React from 'react';
import type { ReviewResultsProps } from '../types';
import { APP_STRINGS } from '../constants/strings';
import { formatDate, downloadAsFile } from '../utils/helpers';
import ScoreDisplay from './ScoreDisplay';
import SectionReviewCard from './SectionReviewCard';

const ReviewResults: React.FC<ReviewResultsProps> = ({ review, onReset }) => {
  const handleDownload = () => {
    const content = `
CV ROAST RESULTS
================

Overall Score: ${review.overall_score}/10
Generated: ${formatDate(review.created_at)}

SECTION REVIEWS:
${review.section_reviews.map(section => `
${section.section_name} (${section.score}/10):
${section.feedback}

Suggestions:
${section.suggestions.map(s => `• ${s}`).join('\n')}
`).join('\n')}

STRENGTHS:
${review.strengths.map(s => `• ${s}`).join('\n')}

AREAS FOR IMPROVEMENT:
${review.improvements.map(i => `• ${i}`).join('\n')}

FUNNY OBSERVATION:
${review.funny_observation}

OVERALL RECOMMENDATION:
${review.overall_recommendation}

---
Generated by RoastUme 🔥
    `;

    downloadAsFile(content.trim(), 'cv-roast-results.txt', 'text/plain');
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-8">
      {/* Header with Score */}
      <div className="text-center bg-gradient-to-br from-primary-50 to-secondary-50 rounded-xl p-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-6">
          {APP_STRINGS.RESULTS_TITLE}
        </h2>
        
        <div className="flex flex-col items-center space-y-4">
          <ScoreDisplay 
            score={review.overall_score} 
            size="lg" 
            showLabel={true}
          />
          
          <p className="text-gray-600 text-sm">
            Generated on {formatDate(review.created_at)}
          </p>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-wrap gap-4 justify-center">
        <button
          onClick={handleDownload}
          className="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 transition-colors duration-200"
        >
          <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m0 0l3-3m-6 2a9 9 0 1118 0 9 9 0 01-18 0z" />
          </svg>
          {APP_STRINGS.DOWNLOAD_REVIEW}
        </button>
        
        <button
          onClick={onReset}
          className="inline-flex items-center px-6 py-3 border border-gray-300 text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 transition-colors duration-200"
        >
          <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
          {APP_STRINGS.UPLOAD_ANOTHER}
        </button>
      </div>

      {/* Section Reviews */}
      <div>
        <h3 className="text-2xl font-bold text-gray-900 mb-6 text-center">
          {APP_STRINGS.FEEDBACK_TITLE}
        </h3>
        
        <div className="grid gap-6 md:grid-cols-1 lg:grid-cols-2">
          {review.section_reviews.map((section, index) => (
            <SectionReviewCard 
              key={section.section_name} 
              section={section} 
              index={index}
            />
          ))}
        </div>
      </div>

      {/* Strengths */}
      <div className="bg-green-50 rounded-lg p-6 border-l-4 border-green-400">
        <div className="flex items-start">
          <div className="text-2xl mr-3">✅</div>
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-green-900 mb-3">
              {APP_STRINGS.STRENGTHS_TITLE}
            </h3>
            <ul className="space-y-2">
              {review.strengths.map((strength, index) => (
                <li key={index} className="text-green-800 flex items-start">
                  <span className="text-green-600 mr-2">•</span>
                  <span>{strength}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Improvements */}
      <div className="bg-yellow-50 rounded-lg p-6 border-l-4 border-yellow-400">
        <div className="flex items-start">
          <div className="text-2xl mr-3">🎯</div>
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-yellow-900 mb-3">
              {APP_STRINGS.IMPROVEMENTS_TITLE}
            </h3>
            <ul className="space-y-2">
              {review.improvements.map((improvement, index) => (
                <li key={index} className="text-yellow-800 flex items-start">
                  <span className="text-yellow-600 mr-2">•</span>
                  <span>{improvement}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Funny Observation */}
      <div className="bg-blue-50 rounded-lg p-6 border-l-4 border-blue-400">
        <div className="flex items-start">
          <div className="text-2xl mr-3">😄</div>
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-blue-900 mb-3">
              {APP_STRINGS.FUNNY_OBSERVATION_TITLE}
            </h3>
            <p className="text-blue-800 italic">
              "{review.funny_observation}"
            </p>
          </div>
        </div>
      </div>

      {/* Overall Recommendation */}
      <div className="bg-gray-50 rounded-lg p-6 border-l-4 border-gray-400">
        <div className="flex items-start">
          <div className="text-2xl mr-3">📋</div>
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-gray-900 mb-3">
              {APP_STRINGS.RECOMMENDATION_TITLE}
            </h3>
            <p className="text-gray-800 leading-relaxed">
              {review.overall_recommendation}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReviewResults;
